### ISSUE TITLE
Can't read the transform.txt file

### ISSUE THREAD

**Issue by WWGate** [grebtsew/FloorplanToBlender3d#16]
Hello,

Thank you for this amazing script!
I got this error message when I try an example, that the script could not find the transform.txt file even though I checked and it's in the correct path

` File "<string>", line 1, in <module>
  File "D:\ai_projects\FloorplanToBlender3d\Blender/floorplan_to_3dObject_in_blender.py", line 480, in <module>
    main(sys.argv)
  File "D:\ai_projects\FloorplanToBlender3d\Blender/floorplan_to_3dObject_in_blender.py", line 157, in main
    create_floorplan(base_path, program_path, i)
  File "D:\ai_projects\FloorplanToBlender3d\Blender/floorplan_to_3dObject_in_blender.py", line 185, in create_floorplan
    transform = read_from_file(path_to_transform_file)
  File "D:\ai_projects\FloorplanToBlender3d\Blender/floorplan_to_3dObject_in_blender.py", line 48, in read_from_file
    with open(file_path + ".txt", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/d/ai_projects/FloorplanToBlender3d/Data/0/transform.txt'
Traceback (most recent call last):
  File "main.py", line 183, in <module>
    create_blender_project(data_paths)
  File "main.py", line 34, in create_blender_project
    check_output(
  File "/home/fadi/miniconda3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/fadi/miniconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/mnt/c/Program Files/Blender Foundation/Blender 3.1/blender.exe', '-noaudio', '--background', '--python', 'Blender/floorplan_to_3dObject_in_blender.py', '/mnt/d/ai_projects/FloorplanToBlender3d', '/Target/floorplan.blend', 'Data/0/']' returned non-zero exit status 1.`

any help is much appreciated

Best regards

**Comment by grebtsew** [comment]
Hi @WWGate!

Thanks for trying the project and submitting an issue!

I agree, this issue seems to be related to unexisting paths.

How are you executing the implementation? Which OS? On Docker? Are you in the project folder when you run?

You seem to be running the implementation on a different harddrive then blender. One quick fix could be to move the project to the same drive as blender (I have not tried running on seperate drives myself, so might be an issue with paths here). 

Can you check that all these paths exists (i.e. cd `path`):
`/mnt/c/Program Files/Blender Foundation/Blender 3.1/`,
`/mnt/d/ai_projects/FloorplanToBlender3d/`,
`D:\ai_projects\FloorplanToBlender3d/`

Cheers,
@grebtsew

**Comment by grebtsew** [comment]
I'm closing this issue due to inactivity.
