### ISSUE TITLE
Help! What do I need to do to fix this bug?

### ISSUE THREAD

**Issue by hughrobs** [grebtsew/FloorplanToBlender3d#22]
Traceback (most recent call last):
  File "/home/floorplan_to_blender/main.py", line 173, in <module>
    data_paths = [execution.simple_single(floorplans[0])]
  File "/home/floorplan_to_blender/FloorplanToBlenderLib/execution.py", line 21, in simple_single
    filepath, _ = generate.generate_all_files(floorplan, show)
  File "/home/floorplan_to_blender/FloorplanToBlenderLib/generate.py", line 39, in generate_all_files
    floorplan.scale[0] * world_scale[0],
AttributeError: 'generator' object has no attribute 'scale'
--- Done ---

**Comment by frankkim1108** [comment]
I think that the code is not reading your floorplan correctly. 
Are you using a different image instead of the example image by changing the image path in the default.ini file?

**Comment by hughrobs** [comment]
> I think that the code is not reading your floorplan correctly.
> Are you using a different image instead of the example image by changing the image path in the default.ini file?

I am trying to get it running by clearing cache and setting all configs to default. It successfully runs when I start the docker image and then closes saying that is has stored the file in Targets, but I cannot find where Targets is located.

**Comment by grebtsew** [comment]
Hello @hughrobs,

If I understand correctly you are running the implementation via docker-compose. Then the `/home/floorplan_to_blender/Target/` folder is volumed (shared between filesystems) to `/path/to/project/Target/`. A Target folder will be created in the project directory.

I hope that answers you question. For the initial error, it would be helpful to know exactly how you executed the program and perhaps an example image, so that I can reproduce the bug.

Cheers,
@grebtsew

**Comment by grebtsew** [comment]
I'm closing this issue due to inactivity.
